# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Run s a set of commands using the runners shell
      - name: Setup Bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: '3.1.0'
          
          
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.5' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          
          
      - name: install deepspeech
        run: |
          git clone https://github.com/mozilla/DeepSpeech.git
          cd DeepSpeech
          git submodule sync tensorflow/
          git submodule update --init tensorflow/
      - name: TensorFlow Configure with Bazel
        run: |
          cd DeepSpeech/tensorflow
          ./configure
      - name: Compile DeepSpeech
        run: |
          cd DeepSpeech/tensorflow/tensorflow
          bazel --version
          bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so
            
      - name: Update Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "release"
          prerelease: true
          title: "test release text"
          files: DeepSpeech/tensorflow/tensorflow/native_client/

